const $=id=>document.getElementById(id), message=$('message');
function setBusy(button,busy,text){button.disabled=busy;button.dataset.label??=button.textContent;button.textContent=busy?text:button.dataset.label}
function showError(e){message.textContent=e.message||String(e)}
$('reference').addEventListener('change',e=>{$('fileName').textContent=e.target.files[0]?.name||'未选择文件'});
 $('refine').addEventListener('click',async()=>{message.textContent='';const prompt=$('prompt').value.trim();if(!prompt)return showError(new Error('请先填写原始提示词'));const b=$('refine');setBusy(b,true,'润色中...');try{const r=await fetch('/api/refine',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({apiKey:$('refineKey').value,prompt})});const d=await r.json();if(!r.ok)throw new Error(d.error);$('prompt').value=d.refined;message.style.color='#477355';message.textContent='提示词已润色，可以继续调整或生成。'}catch(e){showError(e)}finally{setBusy(b,false)}});
const queue=[];let queueRunning=false,nextJobId=1;
const queueLabels={queued:'排队中',running:'生成中',done:'已完成',failed:'失败'};
function renderQueue(){const list=$('queueList');const active=queue.filter(job=>job.status==='queued'||job.status==='running').length;const done=queue.filter(job=>job.status==='done').length;const failed=queue.filter(job=>job.status==='failed').length;$('queueSummary').textContent=`${queue.length} 个任务 · ${active} 个进行中`;if(!queue.length){list.innerHTML='<p class="queueEmpty">暂无任务</p>';return}list.innerHTML='';for(const job of queue){const item=document.createElement('div');item.className='queueItem';item.dataset.status=job.status;const prompt=document.createElement('div');prompt.className='queuePrompt';prompt.textContent=job.prompt;const meta=document.createElement('div');meta.className='queueMeta';meta.textContent=`${job.model} · ${job.size}`;const text=document.createElement('div');text.append(prompt,meta);const status=document.createElement('span');status.className='queueStatus';status.textContent=job.error||queueLabels[job.status];const dot=document.createElement('i');dot.className='queueDot';item.append(dot,text,status);list.append(item)}if(done+failed===queue.length&&queue.length) $('queueSummary').textContent=`${queue.length} 个任务 · 已完成 ${done} · 失败 ${failed}`}
function showGenerated(data,job){const src=data.url||`data:image/png;base64,${data.b64_json}`;$('resultImage').src=src;$('download').href=src;$('usedPrompt').textContent=data.revised_prompt||job.prompt;$('resultMeta').textContent=`${job.model} · ${data.endpoint==='edits'?'参考图编辑':'文生图'}`;$('empty').classList.add('hidden');$('output').classList.remove('hidden')}
async function runJob(job){const form=new FormData();if(job.apiKey)form.append('apiKey',job.apiKey);form.append('prompt',job.prompt);form.append('model',job.model);form.append('size',job.size);if(job.reference)form.append('image',job.reference);const response=await fetch('/api/generate',{method:'POST',body:form});const data=await response.json();if(!response.ok)throw new Error(data.error||'生图失败');showGenerated(data,job)}
async function processQueue(){if(queueRunning)return;queueRunning=true;try{while(true){const job=queue.find(item=>item.status==='queued');if(!job)break;job.status='running';renderQueue();try{await runJob(job);job.status='done';message.style.color='#477355';message.textContent='图片生成完成。'}catch(error){job.status='failed';job.error=error.message;showError(error)}renderQueue()}}finally{queueRunning=false;renderQueue()}}
$('generate').addEventListener('click',()=>{message.textContent='';const prompt=$('prompt').value.trim();if(!prompt)return showError(new Error('请填写提示词'));queue.push({id:nextJobId++,status:'queued',prompt,model:$('model').value,size:$('size').value,apiKey:$('imageKey').value.trim(),reference:$('reference').files[0]||null});renderQueue();message.style.color='#68766d';message.textContent='任务已加入生成队列。';processQueue()});
$('clearQueue').addEventListener('click',()=>{for(let i=queue.length-1;i>=0;i--)if(queue[i].status==='done'||queue[i].status==='failed')queue.splice(i,1);renderQueue()});
renderQueue();
