const $=id=>document.getElementById(id), message=$('message');
function setBusy(button,busy,text){button.disabled=busy;button.dataset.label??=button.textContent;button.textContent=busy?text:button.dataset.label}
function showError(e){message.textContent=e.message||String(e)}
const referenceRoles=['产品细节','动作指导','整体氛围'];
let selectedReferences=[null,null,null];
function isValidReference(file){const mpo=/\.mpo$/i.test(file.name)||file.type==='image/mpo';return mpo||(/\.(png|jpe?g|webp)$/i.test(file.name)&&['image/png','image/jpeg','image/webp'].includes(file.type))}
function setReferenceAt(index,file){if(!file)return;if(!isValidReference(file)){showError(new Error('参考图格式不支持，请使用 PNG、JPG、WebP 或 MPO。'));return}selectedReferences[index]=file;renderReferencePreviews()}
function renderReferencePreviews(){const preview=$('referencePreview'),previewWrap=$('referencePreviewWrap');preview.replaceChildren();selectedReferences.forEach((file,index)=>{const item=document.createElement('div');item.className='referencePreviewItem';item.dataset.slot=index;const role=document.createElement('strong');role.className='referenceRole';role.textContent=`${index+1}. ${referenceRoles[index]}`;item.append(role);const slotInput=document.createElement('input');slotInput.type='file';slotInput.className='referenceSlotInput';slotInput.accept='image/png,image/jpeg,image/webp,image/mpo,.mpo';slotInput.addEventListener('change',event=>{setReferenceAt(index,event.target.files[0]);event.target.value='' });item.append(slotInput);if(file){const image=document.createElement('img');image.src=URL.createObjectURL(file);image.alt=`${referenceRoles[index]}：${file.name}`;const remove=document.createElement('button');remove.type='button';remove.className='referenceRemove';remove.textContent='×';remove.title=`移除 ${file.name}`;remove.setAttribute('aria-label',`移除 ${file.name}`);remove.addEventListener('click',event=>{event.stopPropagation();selectedReferences[index]=null;renderReferencePreviews()});item.append(image,remove)}else{const empty=document.createElement('span');empty.className='referenceEmpty';empty.textContent='点击或拖拽到此处上传';empty.addEventListener('click',()=>slotInput.click());item.append(empty);item.addEventListener('click',event=>{if(event.target===item)slotInput.click()})}item.addEventListener('dragover',event=>{event.preventDefault();item.classList.add('dragging')});item.addEventListener('dragleave',()=>item.classList.remove('dragging'));item.addEventListener('drop',event=>{event.preventDefault();item.classList.remove('dragging');setReferenceAt(index,event.dataTransfer.files[0])});preview.append(item)});$('fileName').textContent=selectedReferences.filter(Boolean).map(file=>file.name).join('、')||'未选择文件';previewWrap.classList.remove('hidden')}
function addReferenceToFirstEmpty(file){const index=selectedReferences.findIndex(entry=>!entry);if(index<0){showError(new Error('最多支持 3 张参考图。'));return}setReferenceAt(index,file)}
$('reference').addEventListener('change',e=>{const files=Array.from(e.target.files||[]);e.target.value='';if(files.length>1)return showError(new Error('请分别拖入对应的三行槽位，每行上传一张参考图。'));addReferenceToFirstEmpty(files[0])});
const referenceDropzone=$('reference').closest('.upload');referenceDropzone.addEventListener('dragover',event=>{event.preventDefault();referenceDropzone.classList.add('dragging')});referenceDropzone.addEventListener('dragleave',()=>referenceDropzone.classList.remove('dragging'));referenceDropzone.addEventListener('drop',event=>{event.preventDefault();referenceDropzone.classList.remove('dragging');const files=Array.from(event.dataTransfer.files||[]);if(files.length>1)return showError(new Error('请分别拖入对应的三行槽位，每行上传一张参考图。'));addReferenceToFirstEmpty(files[0])});
 $('refine').addEventListener('click',async()=>{message.textContent='';const prompt=$('prompt').value.trim();if(!prompt)return showError(new Error('请先填写原始提示词'));const b=$('refine');setBusy(b,true,'润色中...');try{const r=await fetch('/api/refine',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({apiKey:$('refineKey').value,prompt})});const d=await r.json();if(!r.ok)throw new Error(d.error);$('prompt').value=d.refined;message.style.color='#477355';message.textContent='提示词已润色，可以继续调整或生成。'}catch(e){showError(e)}finally{setBusy(b,false)}});
const queue=[];let queueRunning=false,nextJobId=1;const queueStorageKey='image-prompt-queue-v1';
function persistQueue(){try{const saved=queue.filter(job=>job.status==='done'||job.status==='failed').map(({id,status,prompt,model,size,source,error})=>({id,status,prompt,model,size,source:source&&(source.startsWith('http')||source.length<500000?source:null),error}));localStorage.setItem(queueStorageKey,JSON.stringify(saved))}catch(error){console.warn('Could not persist queue history',error)}}
function restoreQueue(){try{const saved=JSON.parse(localStorage.getItem(queueStorageKey)||'[]');if(!Array.isArray(saved))return;for(const job of saved){if(!job?.prompt||!['done','failed'].includes(job.status))continue;queue.push({...job,reference:null,references:null,apiKey:''});nextJobId=Math.max(nextJobId,Number(job.id||0)+1)}}catch(error){console.warn('Could not restore queue history',error)}}
const queueLabels={queued:'排队中',running:'生成中',done:'已完成',failed:'失败'};
function openPreview(job){if(!job.source)return;$('previewImage').src=job.source;$('previewDownload').href=job.source;$('previewPrompt').textContent=job.prompt;$('previewModal').classList.remove('hidden')}
function deleteJob(job){const index=queue.findIndex(item=>item.id===job.id);if(index<0)return;queue.splice(index,1);if(!$('previewModal').classList.contains('hidden'))$('previewModal').classList.add('hidden');renderQueue()}
function rerunJob(job){$('prompt').value=job.prompt;if([...$('model').options].some(option=>option.value===job.model))$('model').value=job.model;if([...$('size').options].some(option=>option.value===job.size))$('size').value=job.size;$('prompt').focus();message.style.color='#68766d';message.textContent='已填充原提示词和尺寸，请确认后点击生成图片。'}
function renderQueue(){persistQueue();const list=$('queueList');const active=queue.filter(job=>job.status==='queued'||job.status==='running').length;const done=queue.filter(job=>job.status==='done').length;const failed=queue.filter(job=>job.status==='failed').length;$('queueSummary').textContent=`${queue.length} 个任务 · ${active} 个进行中`;if(!queue.length){list.innerHTML='<p class="queueEmpty">暂无任务</p>';return}list.innerHTML='';for(const job of queue){const item=document.createElement('div');item.className='queueItem';item.dataset.status=job.status;const body=document.createElement('div');body.className='queueBody';const prompt=document.createElement('div');prompt.className='queuePrompt';prompt.textContent=job.prompt;const meta=document.createElement('div');meta.className='queueMeta';meta.textContent=`${job.model} · ${job.size}`;body.append(prompt,meta);const status=document.createElement('span');status.className='queueStatus';status.textContent=job.error||queueLabels[job.status];const thumb=document.createElement('button');thumb.className='queueThumb';thumb.type='button';if(job.source){const image=document.createElement('img');image.src=job.source;image.alt='生成结果';thumb.append(image);thumb.addEventListener('click',()=>openPreview(job))}else thumb.textContent=job.status==='running'?'…':'';const actions=document.createElement('div');actions.className='queueActions';if(job.source){const preview=document.createElement('button');preview.type='button';preview.className='queueAction';preview.textContent='预览';preview.addEventListener('click',()=>openPreview(job));const download=document.createElement('a');download.className='queueAction';download.textContent='下载';download.href=job.source;download.download=`generated-${job.id}.png`;actions.append(preview,download)}if(job.status==='done'||job.status==='failed'){const rerun=document.createElement('button');rerun.type='button';rerun.className='queueAction rerun';rerun.textContent='再生成';rerun.addEventListener('click',()=>rerunJob(job));const remove=document.createElement('button');remove.type='button';remove.className='queueAction queueDelete';remove.textContent='删除';remove.addEventListener('click',()=>deleteJob(job));actions.append(rerun,remove)}const dot=document.createElement('i');dot.className='queueDot';item.append(thumb,dot,body,status,actions);list.append(item)}if(done+failed===queue.length&&queue.length) $('queueSummary').textContent=`${queue.length} 个任务 · 已完成 ${done} · 失败 ${failed}`}
function showGenerated(data,job){job.source=data.url||`data:image/png;base64,${data.b64_json}`}
async function runJob(job){const references=(job.references||((job.reference&&[job.reference])||[])).filter(Boolean);const form=new FormData();if(job.apiKey)form.append('apiKey',job.apiKey);const roleHint=references.length?`\n\n参考图使用规则：${references.map((_,index)=>`第${index+1}张为${referenceRoles[index]}。${index===0?'产品细节必须保持一致，不得改变产品外形、结构、材质、颜色或关键细节。':index===1?'动作指导仅用于约束姿态、受力和真实物理关系，避免不可能的动作。':'整体氛围仅作为镜头语言、色调、光线和滤镜参考，不改变产品本身。'}`).join('\n')}`:'';form.append('prompt',job.prompt+roleHint);form.append('model',job.model);form.append('quality','max');form.append('size',job.size);for(const reference of references)form.append('image',reference);const response=await fetch('/api/generate',{method:'POST',body:form});const data=await response.json();if(!response.ok)throw new Error(data.error||'生图失败');showGenerated(data,job)}
async function processQueue(){if(queueRunning)return;queueRunning=true;try{while(true){const jobs=queue.filter(item=>item.status==='queued');if(!jobs.length)break;jobs.forEach(job=>{job.status='running'});renderQueue();const results=await Promise.allSettled(jobs.map(job=>runJob(job)));results.forEach((result,index)=>{const job=jobs[index];if(result.status==='fulfilled'){job.status='done'}else{job.status='failed';job.error=result.reason?.message||'生图失败'}});message.style.color=results.some(result=>result.status==='rejected')?'#b64b43':'#477355';message.textContent=results.some(result=>result.status==='rejected')?'部分图片生成失败。':'图片生成完成。';renderQueue()}}finally{queueRunning=false;renderQueue()}}
 $('generate').addEventListener('click',()=>{message.textContent='';const prompt=$('prompt').value.trim();if(!prompt)return showError(new Error('请填写提示词'));if(!selectedReferences[0])return showError(new Error('请先上传第 1 张产品细节图。'));if(selectedReferences[2]&&!selectedReferences[1])return showError(new Error('请先填写第 2 张动作指导图，再添加第 3 张整体氛围图。'));const references=[...selectedReferences].filter(Boolean);const quantity=Number($('quantity').value||1);for(let i=0;i<quantity;i++)queue.push({id:nextJobId++,status:'queued',prompt,model:$('model').value,size:$('size').value,apiKey:$('imageKey').value.trim(),references});renderQueue();message.style.color='#68766d';message.textContent=`已加入 ${quantity} 个生成任务。质量：Max。`;processQueue()});
$('clearQueue').addEventListener('click',()=>{for(let i=queue.length-1;i>=0;i--)if(queue[i].status==='done'||queue[i].status==='failed')queue.splice(i,1);renderQueue()});
$('closePreview').addEventListener('click',()=>$('previewModal').classList.add('hidden'));
$('previewModal').addEventListener('click',event=>{if(event.target.id==='previewModal')event.currentTarget.classList.add('hidden')});
document.addEventListener('keydown',event=>{if(event.key==='Escape')$('previewModal').classList.add('hidden')});
restoreQueue();
renderReferencePreviews();
renderQueue();
