const $=id=>document.getElementById(id), message=$('message');
function setBusy(button,busy,text){button.disabled=busy;button.dataset.label??=button.textContent;button.textContent=busy?text:button.dataset.label}
function showError(e){message.textContent=e.message||String(e)}
$('reference').addEventListener('change',e=>{const file=e.target.files[0];if(!file){$('fileName').textContent='未选择文件';return}const mpo=/\.mpo$/i.test(file.name)||file.type==='image/mpo';const valid=mpo||(/\.(png|jpe?g|webp)$/i.test(file.name)&&['image/png','image/jpeg','image/webp'].includes(file.type));if(!valid){e.target.value='';$('fileName').textContent='未选择文件';showError(new Error('参考图格式不支持，请使用 PNG、JPG、WebP 或 MPO。'));return}$('fileName').textContent=mpo?`${file.name}（将使用第一帧）`:file.name});
 $('refine').addEventListener('click',async()=>{message.textContent='';const prompt=$('prompt').value.trim();if(!prompt)return showError(new Error('请先填写原始提示词'));const b=$('refine');setBusy(b,true,'润色中...');try{const r=await fetch('/api/refine',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({apiKey:$('refineKey').value,prompt})});const d=await r.json();if(!r.ok)throw new Error(d.error);$('prompt').value=d.refined;message.style.color='#477355';message.textContent='提示词已润色，可以继续调整或生成。'}catch(e){showError(e)}finally{setBusy(b,false)}});
const queue=[];let queueRunning=false,nextJobId=1;const queueStorageKey='image-prompt-queue-v1';
function persistQueue(){try{const saved=queue.filter(job=>job.status==='done'||job.status==='failed').map(({id,status,prompt,model,size,source,error})=>({id,status,prompt,model,size,source:source&&(source.startsWith('http')||source.length<500000?source:null),error}));localStorage.setItem(queueStorageKey,JSON.stringify(saved))}catch(error){console.warn('Could not persist queue history',error)}}
function restoreQueue(){try{const saved=JSON.parse(localStorage.getItem(queueStorageKey)||'[]');if(!Array.isArray(saved))return;for(const job of saved){if(!job?.prompt||!['done','failed'].includes(job.status))continue;queue.push({...job,reference:null,apiKey:''});nextJobId=Math.max(nextJobId,Number(job.id||0)+1)}}catch(error){console.warn('Could not restore queue history',error)}}
const queueLabels={queued:'排队中',running:'生成中',done:'已完成',failed:'失败'};
function openPreview(job){if(!job.source)return;$('previewImage').src=job.source;$('previewDownload').href=job.source;$('previewPrompt').textContent=job.prompt;$('previewModal').classList.remove('hidden')}
function rerunJob(job){$('prompt').value=job.prompt;if([...$('model').options].some(option=>option.value===job.model))$('model').value=job.model;if([...$('size').options].some(option=>option.value===job.size))$('size').value=job.size;queue.push({id:nextJobId++,status:'queued',prompt:job.prompt,model:$('model').value,size:$('size').value,apiKey:$('imageKey').value.trim(),reference:$('reference').files[0]||null});renderQueue();message.style.color='#68766d';message.textContent='已填充原提示词并加入重新生成队列。';processQueue()}
function renderQueue(){persistQueue();const list=$('queueList');const active=queue.filter(job=>job.status==='queued'||job.status==='running').length;const done=queue.filter(job=>job.status==='done').length;const failed=queue.filter(job=>job.status==='failed').length;$('queueSummary').textContent=`${queue.length} 个任务 · ${active} 个进行中`;if(!queue.length){list.innerHTML='<p class="queueEmpty">暂无任务</p>';return}list.innerHTML='';for(const job of queue){const item=document.createElement('div');item.className='queueItem';item.dataset.status=job.status;const body=document.createElement('div');body.className='queueBody';const prompt=document.createElement('div');prompt.className='queuePrompt';prompt.textContent=job.prompt;const meta=document.createElement('div');meta.className='queueMeta';meta.textContent=`${job.model} · ${job.size}`;body.append(prompt,meta);const status=document.createElement('span');status.className='queueStatus';status.textContent=job.error||queueLabels[job.status];const thumb=document.createElement('button');thumb.className='queueThumb';thumb.type='button';if(job.source){const image=document.createElement('img');image.src=job.source;image.alt='生成结果';thumb.append(image);thumb.addEventListener('click',()=>openPreview(job))}else thumb.textContent=job.status==='running'?'…':'';const actions=document.createElement('div');actions.className='queueActions';if(job.source){const preview=document.createElement('button');preview.type='button';preview.className='queueAction';preview.textContent='预览';preview.addEventListener('click',()=>openPreview(job));const download=document.createElement('a');download.className='queueAction';download.textContent='下载';download.href=job.source;download.download=`generated-${job.id}.png`;actions.append(preview,download)}if(job.status==='done'||job.status==='failed'){const rerun=document.createElement('button');rerun.type='button';rerun.className='queueAction rerun';rerun.textContent='再生成';rerun.addEventListener('click',()=>rerunJob(job));actions.append(rerun)}const dot=document.createElement('i');dot.className='queueDot';item.append(thumb,dot,body,status,actions);list.append(item)}if(done+failed===queue.length&&queue.length) $('queueSummary').textContent=`${queue.length} 个任务 · 已完成 ${done} · 失败 ${failed}`}
function showGenerated(data,job){job.source=data.url||`data:image/png;base64,${data.b64_json}`}
async function runJob(job){const form=new FormData();if(job.apiKey)form.append('apiKey',job.apiKey);form.append('prompt',job.prompt);form.append('model',job.model);form.append('size',job.size);if(job.reference)form.append('image',job.reference);const response=await fetch('/api/generate',{method:'POST',body:form});const data=await response.json();if(!response.ok)throw new Error(data.error||'生图失败');showGenerated(data,job)}
async function processQueue(){if(queueRunning)return;queueRunning=true;try{while(true){const job=queue.find(item=>item.status==='queued');if(!job)break;job.status='running';renderQueue();try{await runJob(job);job.status='done';message.style.color='#477355';message.textContent='图片生成完成。'}catch(error){job.status='failed';job.error=error.message;showError(error)}renderQueue()}}finally{queueRunning=false;renderQueue()}}
$('generate').addEventListener('click',()=>{message.textContent='';const prompt=$('prompt').value.trim();if(!prompt)return showError(new Error('请填写提示词'));const quantity=Number($('quantity').value||1);for(let i=0;i<quantity;i++)queue.push({id:nextJobId++,status:'queued',prompt,model:$('model').value,size:$('size').value,apiKey:$('imageKey').value.trim(),reference:$('reference').files[0]||null});renderQueue();message.style.color='#68766d';message.textContent=`已加入 ${quantity} 个生成任务。`;processQueue()});
$('clearQueue').addEventListener('click',()=>{for(let i=queue.length-1;i>=0;i--)if(queue[i].status==='done'||queue[i].status==='failed')queue.splice(i,1);renderQueue()});
$('closePreview').addEventListener('click',()=>$('previewModal').classList.add('hidden'));
$('previewModal').addEventListener('click',event=>{if(event.target.id==='previewModal')event.currentTarget.classList.add('hidden')});
document.addEventListener('keydown',event=>{if(event.key==='Escape')$('previewModal').classList.add('hidden')});
restoreQueue();
renderQueue();
